Update package.js to reflect current wisebed.js Version
Using wisebed.js version 0.2.4 does not work correctly, as it requires a jquery version above 1.8 and thus needs the fixes for $.ajax introduced in version 0.2.5.

Using 0.2.4 of wisebed.js leads to the following error:
```
			$.ajax({
			  ^
TypeError: undefined is not a function
```